/**
 * Lexiques internes de classification des rayons.
 * Ne pas modifier l’ordre ni les motifs — classifyProduct en dépend.
 */

export function includesAny(haystack: string, needles: readonly string[]): boolean {
  return needles.some((n) => haystack.includes(n));
}

/** Mot entier (évite « ail » dans « mayonnaise », « riz » dans « maïs », etc.). */
function hasWord(haystack: string, word: string): boolean {
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?:^|\\s)${escaped}(?:\\s|$)`).test(haystack);
}

export function hasAnyWord(haystack: string, words: readonly string[]): boolean {
  return words.some((w) => hasWord(haystack, w));
}

// --- Motifs / lexiques (ordre de priorité dans classifyProduct) ---

export const SURGELES_MARKERS = [
  "surgele",
  "surgeles",
  "congele",
  "congeles",
  "congelateur",
  "glace",
  "glaces",
  "sorbet",
  "sorbets",
  "glacon",
  "glacons",
  "pizza surgelee",
  "frites surgelees",
] as const;

export const MAISON_HYGIENE = [
  "liquide vaisselle",
  "lessive",
  "eponge",
  "eponges",
  "nettoyant",
  "multi usages",
  "multi-usages",
  "sac poubelle",
  "sacs poubelle",
  "papier absorbant",
  "sopalin",
  "papier toilette",
  "pq",
  "mouchoir",
  "mouchoirs",
  "dentifrice",
  "brosse a dents",
  "gel douche",
  "shampoing",
  "shampooing",
  "savon",
  "desodorisant",
  "javel",
  "detergent",
  "assouplissant",
  "essuie tout",
  "essuie-tout",
  "coton tige",
  "rasoir",
  "apres shampoing",
  "apres-shampoing",
  "pansement",
  "pansements",
  "pensement",
  "pensements",
  "medicament",
  "medicaments",
  "doliprane",
  "paracetamol",
  "aspirine",
  "sparadrap",
  "compresse",
  "compresses",
  "pharmacie",
] as const;

/** Conserves / bocaux → épicerie (avant fruits/protéines frais). */
export const EPICERIE_CONSERVE_MARKERS = [
  "conserve",
  "conserves",
  "en boite",
  "en boites",
  "boite de",
  "bocal",
  "bocaux",
  "en conserve",
  "sauce tomate",
  "coulis de tomate",
  "concentre de tomate",
  "tomate pelee",
  "tomates pelees",
  "thon en boite",
  "sardine",
  "sardines",
  "maquereau en boite",
] as const;

/** Produits secs / ambiants qui citent une protéine mais restent en épicerie. */
export const EPICERIE_OVERRIDE_MARKERS = [
  "bouillon",
  "fond de veau",
  "fond de volaille",
  "cube de",
  "cubes de",
] as const;

const LAITIERS_VIANDES = [
  // Laitiers
  "lait",
  "fromage",
  "beurre",
  "yaourt",
  "yogourt",
  "yoghourt",
  "creme fraiche",
  "creme liquide",
  "creme entiere",
  "mascarpone",
  "ricotta",
  "mozzarella",
  "burrata",
  "feta",
  "parmesan",
  "comte",
  "chevre",
  "emmental",
  "gruyere",
  "camembert",
  "brie",
  "skyr",
  // Œufs
  "oeuf",
  "oeufs",
  // Viandes & charcuterie
  "viande",
  "boeuf",
  "steak",
  "poulet",
  "dinde",
  "porc",
  "bacon",
  "jambon",
  "saucisse",
  "saucisses",
  "saucisson",
  "agneau",
  "veau",
  "canard",
  "lapin",
  "lardon",
  "lardons",
  "chorizo",
  "merguez",
  "escalope",
  "cotelette",
  "roti",
  "hache",
  "charcuterie",
  "cuisse de",
  "filet de boeuf",
  "filet mignon",
  "hauts de cuisse",
  // Poissons & fruits de mer (frais / rayon frais)
  "poisson",
  "saumon",
  "cabillaud",
  "thon frais",
  "crevette",
  "crevettes",
  "moule",
  "moules",
  "colin",
  "lieu noir",
  "dorade",
  "truite",
  "sole",
  "maquereau",
  "sardine fraiche",
  "fruit de mer",
  "fruits de mer",
  "calamar",
  "encornet",
  "st jacques",
  "saint jacques",
  // Alternatives végétales / protéines végétales
  "tofu",
  "seitan",
  "tempeh",
  "lait de soja",
  "lait d amande",
  "lait d avoine",
  "lait vegetal",
  "lait vegetaux",
  "yaourt vegetal",
  "yaourt de soja",
  "creme vegetale",
  "creme de soja",
  "fromage vegetal",
  "steak vegetal",
  "galette vegetarienne",
  "galettes vegetariennes",
  "hamburger vegetal",
  "proteine de soja",
] as const;

export const FRUITS_LEGUMES = [
  // Fruits
  "pomme",
  "pommes",
  "banane",
  "bananes",
  "fraise",
  "fraises",
  "citron",
  "citrons",
  "orange",
  "oranges",
  "raisin",
  "raisins",
  "pasteque",
  "pasteques",
  "myrtille",
  "myrtilles",
  "peche",
  "peches",
  "poire",
  "poires",
  "ananas",
  "kiwi",
  "kiwis",
  "cerise",
  "cerises",
  "mangue",
  "mangues",
  "abricot",
  "abricots",
  "framboise",
  "framboises",
  "mure",
  "mures",
  "melon",
  "melons",
  "pamplemousse",
  "clementine",
  "clementines",
  "mandarine",
  "mandarines",
  "figue",
  "figues",
  "prune",
  "prunes",
  "nectarine",
  "nectarines",
  "fruit",
  "fruits",
  // Légumes
  "tomate",
  "tomates",
  "tomate cerise",
  "tomates cerises",
  "carotte",
  "carottes",
  "poivron",
  "poivrons",
  "concombre",
  "concombres",
  "courgette",
  "courgettes",
  "aubergine",
  "aubergines",
  "salade",
  "laitue",
  "mesclun",
  "roquette",
  "brocoli",
  "brocolis",
  "chou",
  "choux",
  "chou fleur",
  "epinard",
  "epinards",
  "haricot vert",
  "haricots verts",
  "petit pois",
  "petits pois",
  "radis",
  "betterave",
  "betteraves",
  "celeri",
  "fenouil",
  "poireau",
  "poireaux",
  "navet",
  "navets",
  "panais",
  "asperge",
  "asperges",
  "artichaut",
  "artichauts",
  "courge",
  "potiron",
  "potimarron",
  "mais doux",
  "avocat",
  "avocats",
  "legume",
  "legumes",
  // Bulbes & tubercules
  "oignon",
  "oignons",
  "ail",
  "echalote",
  "echalotes",
  "gingembre",
  "patate douce",
  "patates douces",
  "pomme de terre",
  "pommes de terre",
  "grenaille",
  // Champignons & herbes
  "champignon",
  "champignons",
  "basilic",
  "persil",
  "menthe",
  "ciboulette",
  "coriandre",
  "aneth",
  "thym",
  "romarin",
  "estragon",
  "laurier",
  "herbes fraiches",
  "herbe fraiche",
  "herbes aromatiques",
] as const;

export const EPICERIE_FECULENTS = [
  // Céréales & féculents
  "pate",
  "pates",
  "riz",
  "farine",
  "semoule",
  "quinoa",
  "flocons d avoine",
  "avoine",
  "cereale",
  "cereales",
  "boulgour",
  "couscous",
  "polenta",
  "mais",
  // Boulangerie
  "pain",
  "pain de mie",
  "brioche",
  "tortilla",
  "tortillas",
  "biscotte",
  "biscottes",
  "baguette",
  // Légumineuses
  "haricot rouge",
  "haricots rouges",
  "haricot blanc",
  "haricots blancs",
  "lentille",
  "lentilles",
  "pois chiche",
  "pois chiches",
  "legumineuse",
  "legumineuses",
  // Huiles & condiments
  "huile",
  "vinaigre",
  "sel",
  "poivre",
  "epice",
  "epices",
  "sauce soja",
  "moutarde",
  "mayonnaise",
  "ketchup",
  "bouillon",
  "paprika",
  "curcuma",
  "cumin",
  "cannelle",
  "capre",
  "capres",
  "olive",
  "olives",
  "fleur de sel",
  // Sucrants & pâtisserie
  "sucre",
  "miel",
  "sirop d erable",
  "chocolat",
  "poudre a lever",
  "levure",
  "noix",
  "cacahuete",
  "cacahuetes",
  "amande",
  "amandes",
  "noisette",
  "noisettes",
  "praline",
  "cacao",
  "vanille",
  "vin",
  "biere",
] as const;

export function matchesLaitiersViandes(n: string): boolean {
  if (hasWord(n, "laitue")) return false;

  if (
    /lait\s+(d |de )?(amande|avoine|soja|riz|coco|vegetal)/.test(n) ||
    /(yaourt|creme|fromage)\s+(vegetal|de soja|d amande|d avoine)/.test(n) ||
    /(steak|galette|burger|nugget)s?\s+veget/.test(n)
  ) {
    return true;
  }

  if (includesAny(n, LAITIERS_VIANDES)) return true;

  return hasAnyWord(n, [
    "lait",
    "oeuf",
    "oeufs",
    "tofu",
    "seitan",
    "tempeh",
    "thon",
    "saumon",
    "cabillaud",
  ]);
}
