import type { UnitCode } from "@/lib/units";

/** Alias legacy → code canonique (localStorage / IA / anciennes recettes). */
export const LEGACY_UNIT_MAP: Record<string, UnitCode> = {
  unite: "piece",
  unites: "piece",
  cas: "c_soupe",
  cac: "c_cafe",
};

/** Libellés courts pour l'affichage (sélecteurs, quantités). */
export const UNIT_SHORT_LABELS: Partial<Record<UnitCode, string>> = {
  g: "g",
  kg: "kg",
  ml: "ml",
  cl: "cl",
  l: "L",
  c_cafe: "c.à.c",
  c_soupe: "c.à.s",
  verre: "verre",
  piece: "Pièce",
  gousse: "gousse",
  tranche: "tranche",
  sachet: "sachet",
  pincee: "pincée",
  brin: "brin",
  poignee: "poignée",
  botte: "botte",
  feuille: "feuille",
  qs: "Quantité suffisante",
};

/** Unités dénombrables qui prennent un « s » au pluriel à l'affichage. */
export const PLURALIZED_UNITS: Partial<Record<UnitCode, string>> = {
  piece: "pièce",
  gousse: "gousse",
  tranche: "tranche",
  sachet: "sachet",
  pincee: "pincée",
  brin: "brin",
  poignee: "poignée",
  botte: "botte",
  feuille: "feuille",
};

export const UNIT_ALIASES: Record<string, { unit: UnitCode; factor: number }> = {
  g: { unit: "g", factor: 1 },
  gr: { unit: "g", factor: 1 },
  gramme: { unit: "g", factor: 1 },
  grammes: { unit: "g", factor: 1 },
  kg: { unit: "kg", factor: 1 },
  kilo: { unit: "kg", factor: 1 },
  kilos: { unit: "kg", factor: 1 },
  ml: { unit: "ml", factor: 1 },
  millilitre: { unit: "ml", factor: 1 },
  millilitres: { unit: "ml", factor: 1 },
  cl: { unit: "cl", factor: 1 },
  dl: { unit: "ml", factor: 100 },
  l: { unit: "l", factor: 1 },
  litre: { unit: "l", factor: 1 },
  litres: { unit: "l", factor: 1 },
  cas: { unit: "c_soupe", factor: 1 },
  c_soupe: { unit: "c_soupe", factor: 1 },
  "c a s": { unit: "c_soupe", factor: 1 },
  "cuillere a soupe": { unit: "c_soupe", factor: 1 },
  "cuilleres a soupe": { unit: "c_soupe", factor: 1 },
  tbsp: { unit: "c_soupe", factor: 1 },
  cac: { unit: "c_cafe", factor: 1 },
  c_cafe: { unit: "c_cafe", factor: 1 },
  "c a c": { unit: "c_cafe", factor: 1 },
  "cuillere a cafe": { unit: "c_cafe", factor: 1 },
  "cuilleres a cafe": { unit: "c_cafe", factor: 1 },
  tsp: { unit: "c_cafe", factor: 1 },
  verre: { unit: "verre", factor: 1 },
  verres: { unit: "verre", factor: 1 },
  piece: { unit: "piece", factor: 1 },
  pieces: { unit: "piece", factor: 1 },
  unite: { unit: "piece", factor: 1 },
  unites: { unit: "piece", factor: 1 },
  pce: { unit: "piece", factor: 1 },
  pc: { unit: "piece", factor: 1 },
  pot: { unit: "piece", factor: 1 },
  pots: { unit: "piece", factor: 1 },
  portion: { unit: "piece", factor: 1 },
  portions: { unit: "piece", factor: 1 },
  sachet: { unit: "sachet", factor: 1 },
  sachets: { unit: "sachet", factor: 1 },
  brin: { unit: "brin", factor: 1 },
  brins: { unit: "brin", factor: 1 },
  poignee: { unit: "poignee", factor: 1 },
  poignees: { unit: "poignee", factor: 1 },
  pincee: { unit: "pincee", factor: 1 },
  pincees: { unit: "pincee", factor: 1 },
  tranche: { unit: "tranche", factor: 1 },
  tranches: { unit: "tranche", factor: 1 },
  botte: { unit: "botte", factor: 1 },
  bottes: { unit: "botte", factor: 1 },
  gousse: { unit: "gousse", factor: 1 },
  gousses: { unit: "gousse", factor: 1 },
  feuille: { unit: "feuille", factor: 1 },
  feuilles: { unit: "feuille", factor: 1 },
  qs: { unit: "qs", factor: 1 },
  "quantite suffisante": { unit: "qs", factor: 1 },
  quantite_suffisante: { unit: "qs", factor: 1 },
  quantitesuffisante: { unit: "qs", factor: 1 },
  "au besoin": { unit: "qs", factor: 1 },
  "au gout": { unit: "qs", factor: 1 },
};

export const UNQUANTIFIED_MARKERS = [
  "qs",
  "q s",
  "quantite suffisante",
  "quantitesuffisante",
  "au besoin",
  "quelques",
  "au gout",
  "a volonte",
  "selon gout",
  "selon les gouts",
] as const;
